// Product data for the demo store (no backend).
// Base prices are stored in UAH.
window.STORE_PRODUCTS = [
  {
    id: "np-ice-mint-6000",
    category: "vapes",
    accent: "mint",
    emoji: "🧊",
    old_price_uah: 750,
    price_uah: 500,
    puffs: 6000,
    nicotine: "2% (20mg/ml)",
    i18n: {
      ru: {
        name: "Одноразовый вейп Ice Mint",
        flavor: "Лёд • Мята",
        badge: "Хит",
        desc: "Холодная мята. Ровная тяга. Компактный формат для тех, кто любит свежесть.",
      },
      uk: {
        name: "Одноразовий вейп Ice Mint",
        flavor: "Лід • М'ята",
        badge: "Хіт",
        desc: "Холодна м'ята. Рівна тяга. Компактний формат для тих, хто любить свіжість.",
      },
      en: {
        name: "Disposable Vape Ice Mint",
        flavor: "Ice • Mint",
        badge: "Bestseller",
        desc: "Cold mint profile with a clean hit. Compact format for people who like freshness.",
      },
    },
  },
  {
    id: "np-tropical-5000",
    category: "vapes",
    accent: "tropical",
    emoji: "🥭",
    old_price_uah: 750,
    price_uah: 500,
    puffs: 5000,
    nicotine: "2% (20mg/ml)",
    i18n: {
      ru: {
        name: "Одноразовый вейп Tropical Mix",
        flavor: "Манго • Ананас",
        badge: "Новый вкус",
        desc: "Тропический микс без лишней сладости. Яркий вкус без приторности.",
      },
      uk: {
        name: "Одноразовий вейп Tropical Mix",
        flavor: "Манго • Ананас",
        badge: "Новий смак",
        desc: "Тропічний мікс без зайвої солодкості. Яскравий смак без нудотності.",
      },
      en: {
        name: "Disposable Vape Tropical Mix",
        flavor: "Mango • Pineapple",
        badge: "New flavor",
        desc: "Tropical mix without extra sweetness. Bright taste without being too sugary.",
      },
    },
  },
  {
    id: "np-berry-4500",
    category: "vapes",
    accent: "berry",
    emoji: "🫐",
    old_price_uah: 750,
    price_uah: 500,
    puffs: 4500,
    nicotine: "2% (20mg/ml)",
    i18n: {
      ru: {
        name: "Одноразовый вейп Berry Rush",
        flavor: "Ягоды • Лёгкий холодок",
        badge: "-10% сегодня",
        desc: "Ягодный микс с мягкой прохладой. Сбалансировано — не “компот” и не “леденец”.",
      },
      uk: {
        name: "Одноразовий вейп Berry Rush",
        flavor: "Ягоди • Легкий холодок",
        badge: "-10% сьогодні",
        desc: "Ягідний мікс із м'якою прохолодою. Збалансовано — не “компот” і не “льодяник”.",
      },
      en: {
        name: "Disposable Vape Berry Rush",
        flavor: "Berries • Light chill",
        badge: "-10% today",
        desc: "Berry mix with a soft chill. Balanced — not a candy bomb, not a watered drink.",
      },
    },
  },
  {
    id: "np-cola-4000",
    category: "vapes",
    accent: "cola",
    emoji: "🥤",
    old_price_uah: 750,
    price_uah: 500,
    puffs: 4000,
    nicotine: "2% (20mg/ml)",
    i18n: {
      ru: {
        name: "Одноразовый вейп Cola",
        flavor: "Кола • Лёд",
        badge: "Классика",
        desc: "Кола с холодком. Вкус знакомый, тяга стабильная — отличный “ежедневный” вариант.",
      },
      uk: {
        name: "Одноразовий вейп Cola",
        flavor: "Кола • Лід",
        badge: "Класика",
        desc: "Кола з холодком. Знайомий смак і стабільна тяга — хороший “на щодень” варіант.",
      },
      en: {
        name: "Disposable Vape Cola",
        flavor: "Cola • Ice",
        badge: "Classic",
        desc: "Cola with ice. Familiar taste, stable hit — an easy daily option.",
      },
    },
  },
  {
    id: "np-blueberry-ice-5500",
    category: "vapes",
    accent: "blueberry",
    emoji: "🫐",
    old_price_uah: 750,
    price_uah: 500,
    puffs: 5500,
    nicotine: "2% (20mg/ml)",
    i18n: {
      ru: {
        name: "Одноразовый вейп Blueberry Ice",
        flavor: "Голубика • Лёд",
        badge: "Топ",
        desc: "Голубика с холодком: ярко, чисто, без приторности. Тот самый “синий” вкус.",
      },
      uk: {
        name: "Одноразовий вейп Blueberry Ice",
        flavor: "Лохина • Лід",
        badge: "Топ",
        desc: "Лохина з холодком: яскраво, чисто, без нудотності. Той самий “синій” смак.",
      },
      en: {
        name: "Disposable Vape Blueberry Ice",
        flavor: "Blueberry • Ice",
        badge: "Top",
        desc: "Blueberry with a cold finish: bold, clean, not too sweet. The iconic “blue” vibe.",
      },
    },
  },
  {
    id: "np-watermelon-5200",
    category: "vapes",
    accent: "watermelon",
    emoji: "🍉",
    old_price_uah: 750,
    price_uah: 500,
    puffs: 5200,
    nicotine: "2% (20mg/ml)",
    i18n: {
      ru: {
        name: "Одноразовый вейп Watermelon Chill",
        flavor: "Арбуз • Прохлада",
        badge: "Лето",
        desc: "Сочный арбуз и лёгкая прохлада. Мягкий, но выразительный вкус на каждый день.",
      },
      uk: {
        name: "Одноразовий вейп Watermelon Chill",
        flavor: "Кавун • Прохолода",
        badge: "Літо",
        desc: "Соковитий кавун і легка прохолода. М'який, але виразний смак на щодень.",
      },
      en: {
        name: "Disposable Vape Watermelon Chill",
        flavor: "Watermelon • Chill",
        badge: "Summer",
        desc: "Juicy watermelon with a light chill. Smooth, yet expressive — an easy daily pick.",
      },
    },
  },
  {
    id: "np-grape-4800",
    category: "vapes",
    accent: "grape",
    emoji: "🍇",
    old_price_uah: 750,
    price_uah: 500,
    puffs: 4800,
    nicotine: "2% (20mg/ml)",
    i18n: {
      ru: {
        name: "Одноразовый вейп Grape Soda",
        flavor: "Виноград • Содовая",
        badge: "Неон",
        desc: "Виноградный “содовый” профиль: сладость с пузырьками в ощущениях, без тяжести.",
      },
      uk: {
        name: "Одноразовий вейп Grape Soda",
        flavor: "Виноград • Содова",
        badge: "Неон",
        desc: "Виноградний “содовий” профіль: солодкість із “бульбашками”, без важкості.",
      },
      en: {
        name: "Disposable Vape Grape Soda",
        flavor: "Grape • Soda",
        badge: "Neon",
        desc: "Grape soda profile: sweet, sparkly feel, without being heavy.",
      },
    },
  },
  {
    id: "np-lemon-lime-5000",
    category: "vapes",
    accent: "citrus",
    emoji: "🍋",
    old_price_uah: 750,
    price_uah: 500,
    puffs: 5000,
    nicotine: "2% (20mg/ml)",
    i18n: {
      ru: {
        name: "Одноразовый вейп Lemon Lime",
        flavor: "Лимон • Лайм",
        badge: "Свежо",
        desc: "Цитрусовый удар: лимон и лайм с чёткой кислинкой. Сразу бодрит.",
      },
      uk: {
        name: "Одноразовий вейп Lemon Lime",
        flavor: "Лимон • Лайм",
        badge: "Свіжо",
        desc: "Цитрусовий удар: лимон і лайм із чіткою кислинкою. Одразу бадьорить.",
      },
      en: {
        name: "Disposable Vape Lemon Lime",
        flavor: "Lemon • Lime",
        badge: "Fresh",
        desc: "Citrus punch: lemon and lime with a crisp tang. Instant wake‑up.",
      },
    },
  },
  {
    id: "np-peach-4700",
    category: "vapes",
    accent: "peach",
    emoji: "🍑",
    old_price_uah: 750,
    price_uah: 500,
    puffs: 4700,
    nicotine: "2% (20mg/ml)",
    i18n: {
      ru: {
        name: "Одноразовый вейп Peach Cloud",
        flavor: "Персик • Нежный дым",
        badge: "Мягко",
        desc: "Нежный персик и ощущение “облака”. Для тех, кто любит мягкий сладкий профиль.",
      },
      uk: {
        name: "Одноразовий вейп Peach Cloud",
        flavor: "Персик • Ніжний дим",
        badge: "М'яко",
        desc: "Ніжний персик і відчуття “хмарки”. Для тих, хто любить м'який солодкий профіль.",
      },
      en: {
        name: "Disposable Vape Peach Cloud",
        flavor: "Peach • Soft smoke",
        badge: "Smooth",
        desc: "Soft peach with a cloud‑like feel. For those who like a gentle sweet profile.",
      },
    },
  },
  {
    id: "np-coffee-4200",
    category: "vapes",
    accent: "coffee",
    emoji: "☕",
    old_price_uah: 750,
    price_uah: 500,
    puffs: 4200,
    nicotine: "2% (20mg/ml)",
    i18n: {
      ru: {
        name: "Одноразовый вейп Coffee Caramel",
        flavor: "Кофе • Карамель",
        badge: "Ночь",
        desc: "Кофейный профиль с карамельным хвостом. Не “сироп”, а тёплый вкус.",
      },
      uk: {
        name: "Одноразовий вейп Coffee Caramel",
        flavor: "Кава • Карамель",
        badge: "Ніч",
        desc: "Кавовий профіль із карамельним шлейфом. Не “сироп”, а теплий смак.",
      },
      en: {
        name: "Disposable Vape Coffee Caramel",
        flavor: "Coffee • Caramel",
        badge: "Night",
        desc: "Coffee profile with a caramel tail. Not syrupy — warm and balanced.",
      },
    },
  },
  {
    id: "np-secret-zelensky",
    category: "vapes",
    secret: true,
    accent: "secret",
    emoji: "🕵️",
    old_price_uah: 750,
    price_uah: 500,
    puffs: 5100,
    nicotine: "2% (20mg/ml)",
    i18n: {
      ru: {
        name: "Секретный вкус “Зеленский”",
        flavor: "Лайм • Мята • Неон",
        badge: "Секрет",
        desc: "Спрятанный вкус для своих. Открывается через 21+ — если знаешь фразу.",
      },
      uk: {
        name: "Секретний смак “Зеленський”",
        flavor: "Лайм • М'ята • Неон",
        badge: "Секрет",
        desc: "Схований смак для своїх. Відкривається через 21+ — якщо знаєш фразу.",
      },
      en: {
        name: "Secret Flavor “Zelensky”",
        flavor: "Lime • Mint • Neon",
        badge: "Secret",
        desc: "A hidden flavor for insiders. Unlock it via 21+ if you know the phrase.",
      },
    },
  },
  {
    id: "np-charger-usb",
    category: "accessories",
    accent: "mono",
    emoji: "🔌",
    price_uah: 290,
    puffs: null,
    nicotine: null,
    i18n: {
      ru: {
        name: "Кабель USB‑C",
        flavor: "Аксессуар",
        badge: "Нужно всем",
        desc: "Короткий USB‑C кабель для зарядки совместимых устройств.",
      },
      uk: {
        name: "Кабель USB‑C",
        flavor: "Аксесуар",
        badge: "Потрібно всім",
        desc: "Короткий кабель USB‑C для заряджання сумісних пристроїв.",
      },
      en: {
        name: "USB‑C Cable",
        flavor: "Accessory",
        badge: "Must‑have",
        desc: "Short USB‑C cable for charging compatible devices.",
      },
    },
  },
  {
    id: "np-case",
    category: "accessories",
    accent: "mono",
    emoji: "🧷",
    price_uah: 390,
    puffs: null,
    nicotine: null,
    i18n: {
      ru: {
        name: "Чехол‑капсула",
        flavor: "Аксессуар",
        badge: "Защита",
        desc: "Компактный чехол для переноски. Меньше царапин — больше спокойствия.",
      },
      uk: {
        name: "Чохол‑капсула",
        flavor: "Аксесуар",
        badge: "Захист",
        desc: "Компактний чохол для перенесення. Менше подряпин — більше спокою.",
      },
      en: {
        name: "Capsule Case",
        flavor: "Accessory",
        badge: "Protection",
        desc: "Compact carry case. Fewer scratches, more peace of mind.",
      },
    },
  },
];
